# Generated by Django 5.2 on 2025-11-14 02:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('fecha_salida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['-created'],
            },
        ),
    ]
