# Generated by Django 5.0.6 on 2025-12-11 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajes',
            name='cancelado',
            field=models.BooleanField(default=False, help_text='Si está marcado, el viaje se mostrará como cancelado en el sitio público.', verbose_name='Viaje cancelado'),
        ),
        migrations.AddField(
            model_name='viajes',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud (opcional)'),
        ),
        migrations.AddField(
            model_name='viajes',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud (opcional)'),
        ),
        migrations.AddField(
            model_name='viajes',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de video (YouTube opcional)'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('ciudad', models.CharField(max_length=120)),
                ('estado_texto', models.CharField(max_length=120, verbose_name='Estado')),
                ('personas', models.PositiveIntegerField(default=1)),
                ('mensaje', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='registros.viajes')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-created'],
            },
        ),
    ]
